protocol-union-api:
  replicas: 3
  service:
    nodePort: 30118
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 256

protocol-union-listener:
  resources:
    jvm:
      xmx_megabytes: 6144
      max_direct_memory_megabytes: 1024

protocol-union-meta-loader:
  replicas: 8

protocol-union-indexer:
  enabled: true
  replicas: 3
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 256

protocol-union-worker:
  enabled: true
  replicas: 0
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 128
