protocol-union-api:
  replicas: 3
  service:
    enabled: true
    nodePort: 30118
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 256
  networks:
    common:
    - '{{ include "service.appEnv" $ }}-backend'
    - proxy

protocol-union-listener:
  resources:
    jvm:
      xmx_megabytes: 4096
      max_direct_memory_megabytes: 1024

protocol-union-meta-loader:
  replicas: 3
