protocol-union-api:
  service:
    nodePort: 30418
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 32

protocol-union-meta-loader:
  replicas: 3

protocol-union-indexer:
  replicas: 3
