protocol-union-api:
  image:
    repository: union-service-api
  replicas: 2
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.env" $ }}'
    SERVICE_PREFIX: '{{ include "service.env" $ }}-union'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 384
      max_direct_memory_megabytes: 32
  service:
    enabled: true
  updateConfig:
    order: start-first
  podAnnotations:
    fluentbit.io/parser: logfmt

protocol-union-listener:
  replicas: 1
  image:
    repository: union-service-listener
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.env" $ }}'
    SERVICE_PREFIX: '{{ include "service.env" $ }}-union'
    JAVA_OPTIONS: '-XX:NewRatio=1'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 128
  podAnnotations:
    fluentbit.io/parser: logfmt

protocol-union-meta-loader:
  replicas: 1
  image:
    repository: union-service-meta-loader
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.env" $ }}'
    SERVICE_PREFIX: '{{ include "service.env" $ }}-union'
    JAVA_OPTIONS: '-XX:NewRatio=1'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 512
      max_direct_memory_megabytes: 128
  podAnnotations:
    fluentbit.io/parser: logfmt

protocol-union-indexer:
  replicas: 1
  image:
    repository: union-service-indexer
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.env" $ }}'
    SERVICE_PREFIX: '{{ include "service.env" $ }}-union'
    JAVA_OPTIONS: '-XX:NewRatio=1'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 384
      max_direct_memory_megabytes: 64
  podAnnotations:
    fluentbit.io/parser: logfmt

protocol-union-worker:
  replicas: 1
  image:
    repository: union-service-worker
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.env" $ }}'
    SERVICE_PREFIX: '{{ include "service.env" $ }}-union'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 256
      max_direct_memory_megabytes: 64
  podAnnotations:
    fluentbit.io/parser: logfmt
