protocol-union-api:
  image:
    repository: union-service-api
  replicas: 2
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.env" $ }}'
    SERVICE_PREFIX: '{{ include "service.env" $ }}-union'
    JAVA_OPTIONS: '-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 384
      max_direct_memory_megabytes: 32
  service:
    enabled: true
  updateConfig:
    order: start-first
  networks:
    common:
    - '{{ include "service.env" $ }}-backend'
    - proxy-staging

protocol-union-listener:
  image:
    repository: union-service-listener
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.env" $ }}'
    SERVICE_PREFIX: '{{ include "service.env" $ }}-union'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 1536
      max_direct_memory_megabytes: 128
  networks:
    common:
    - '{{ include "service.env" $ }}-backend'

protocol-union-meta-loader:
  image:
    repository: union-service-meta-loader
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.env" $ }}'
    SERVICE_PREFIX: '{{ include "service.env" $ }}-union'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 256
  networks:
    common:
      - '{{ include "service.env" $ }}-backend'

protocol-union-indexer:
  enabled: false
  image:
    repository: union-service-indexer
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.env" $ }}'
    SERVICE_PREFIX: '{{ include "service.env" $ }}-union'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 512
  networks:
    common:
      - '{{ include "service.env" $ }}-backend'

protocol-union-worker:
  enabled: false
  image:
    repository: union-service-worker
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.env" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.env" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.env" $ }}'
    SERVICE_PREFIX: '{{ include "service.env" $ }}-union'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 512
  networks:
    common:
      - '{{ include "service.env" $ }}-backend'
