protocol-union-api:
  image:
    repository: union-service-api
  replicas: 2
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.appEnv" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.appEnv" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.appEnv" $ }}'
    SERVICE_PREFIX: '{{ include "service.appEnv" $ }}-union'
    JAVA_OPTIONS: '-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 384
      max_direct_memory_megabytes: 32
  updateConfig:
    order: start-first
  networks:
    common:
    - '{{ include "service.appEnv" $ }}-backend'
    - proxy-staging

protocol-union-listener:
  image:
    repository: union-service-listener
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.appEnv" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.appEnv" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.appEnv" $ }}'
    SERVICE_PREFIX: '{{ include "service.appEnv" $ }}-union'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 1536
      max_direct_memory_megabytes: 128
  networks:
    common:
    - '{{ include "service.appEnv" $ }}-backend'

protocol-union-meta-loader:
  image:
    repository: union-service-meta-loader
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.appEnv" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.appEnv" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.appEnv" $ }}'
    SERVICE_PREFIX: '{{ include "service.appEnv" $ }}-union'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 2048
      max_direct_memory_megabytes: 512
  networks:
    common:
      - '{{ include "service.appEnv" $ }}-backend'

protocol-union-search-indexer:
  image:
    repository: union-service-indexer
  environments:
    APPLICATION_ENVIRONMENT: '{{ include "service.appEnv" $ }}'
    CONSUL_ROOT_PATH: '{{ include "service.appEnv" $ }}/protocol/union'
    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.appEnv" $ }}'
    SERVICE_PREFIX: '{{ include "service.appEnv" $ }}-union'
  nodeSelector:
    node.labels.rarible.service: true
  resources:
    jvm:
      xmx_megabytes: 1024
      max_direct_memory_megabytes: 512
  networks:
    common:
      - '{{ include "service.appEnv" $ }}-backend'

#protocol-union-search-reindexer:
#  image:
#    repository: union-service-search-reindexer
#  environments:
#    APPLICATION_ENVIRONMENT: '{{ include "service.appEnv" $ }}'
#    CONSUL_ROOT_PATH: '{{ include "service.appEnv" $ }}/protocol/union'
#    SPRING_PROFILES_ACTIVE: 'consul,{{ include "service.appEnv" $ }}'
#    SERVICE_PREFIX: '{{ include "service.appEnv" $ }}-union'
#  nodeSelector:
#    node.labels.rarible.service: true
#  resources:
#    jvm:
#      xmx_megabytes: 1024
#      max_direct_memory_megabytes: 512
#  networks:
#    common:
#      - '{{ include "service.appEnv" $ }}-backend'
