application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application.name: union-search-reindexer
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  aop:
    proxy-target-class: false
  main:
    banner-mode: log
    web-application-type: reactive

rarible:
  core:
    apm:
      agent:
        enabled: true
        server: http://elk_apm-server:8200
        packages: com.rarible.protocol.union.worker
      web:
        filter:
          enabled: false
      annotation:
        enabled: true

worker:
  search-reindex:
    activity:
      enabled: true
      blockchains:
        - blockchain: ETHEREUM
          enabled: true
        - blockchain: POLYGON
          enabled: true
        - blockchain: FLOW
          enabled: true
        - blockchain: TEZOS
          enabled: true
        - blockchain: SOLANA
          enabled: true
        - blockchain: IMMUTABLEX
          enabled: false
    order:
      enabled: false
      blockchains:
    collection:
      enabled: false
      blockchains:
    ownership:
      enabled: false
      blockchains:
