application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application.name: union-api
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  main:
    banner-mode: log
    web-application-type: reactive

rarible:
  ethereum:
    converter:
      enabled: true
  cache:
    use-locks: true

integration:
  blockchains:
    - blockchain: ETHEREUM
      enabled: ${consul.ethereum.enabled:true}
    - blockchain: POLYGON
      enabled: ${consul.polygon.enabled:true}
    - blockchain: FLOW
      enabled: ${consul.flow.enabled:true}
    - blockchain: TEZOS
      enabled: ${consul.tezos.enabled:true}
      client:
        baseUrl: ${consul.tezos.api.baseUrl}

common:
  producer:
    broker-replica-set: ${kafka.hosts}
  currency:
    refresh:
      cron: "0 0/30 * * * *"

meta:
  ipfsGateway: "https://ipfs.rarible.com/"
  mediaFetchTimeout: 10000
  mediaFetchMaxSize: 10485760
  openSeaProxyUrl: ${consul.meta.openSeaProxyUrl}
