application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application.name: union-listener
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  aop:
    proxy-target-class: false
  main:
    banner-mode: log
    web-application-type: reactive

rarible:
  ethereum:
    converter:
      enabled: true

common:
  producer:
    broker-replica-set: ${kafka.hosts}

listener:
  consumer:
    ethereum:
      broker-replica-set: ${kafka.hosts}
      itemWorkers: 1
      ownershipWorkers: 2
      orderWorkers: 5
    polygon:
      broker-replica-set: ${kafka.hosts}
      itemWorkers: 1
      ownershipWorkers: 1
      orderWorkers: 2
    flow:
      broker-replica-set: ${kafka.hosts}
      itemWorkers: 1,
      ownershipWorkers: 1
      orderWorkers: 1
  reconciliation:
    orderBatchSize: 50
    threadCount: 2


