application:
  project: protocol

server:
  shutdown: graceful
  port: 8080

spring:
  application.name: union-listener
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  aop:
    proxy-target-class: false
  main:
    banner-mode: log
    web-application-type: reactive

rarible:
  ethereum:
    converter:
      enabled: true

listener:
  producer:
    broker-replica-set: ${kafka.hosts}
  consumer:
    ethereum:
      broker-replica-set: ${kafka.hosts}
    poygon:
      broker-replica-set: ${kafka.hosts}
    flow:
      broker-replica-set: ${kafka.hosts}

