openapi: 3.0.3
info:
paths:

components:
  schemas:

################### TEST ######################
    Test:
      type: object
      properties:
        id:
          type: integer

    UnionItemEvent:
      required:
        - eventId
        - itemId
      properties:
        eventId:
          type: string
        itemId:
          type: string

    UnionOwnershipEvent:
      required:
        - eventId
        - ownershipId
      properties:
        eventId:
          type: string
        ownershipId:
          type: string

    UnionOrderEvent:
      required:
        - hash
      properties:
        hash:
          type: string

    #################### Meta - Union ####################

    Meta:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        attributes:
          type: array
          items:
            $ref: "#/components/schemas/MetaAttribute"
        contents:
          type: array
          items:
            $ref: "#/components/schemas/MetaContent"
        raw:
          $ref: "#/components/schemas/Binary"
      required:
        - name

    MetaContent:
      type: object
      properties:
        typeContent:
          type: string
        url:
          type: string
        attributes:
          type: array
          items:
            $ref: "#/components/schemas/MetaAttribute"
      required:
        - typeContent
        - url

    MetaAttribute:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
      required:
        - key
        - value

    #################### Item - Union ####################

    Item:
      type: object
      properties:
        mintedAt:
          type: string
          format: date-time
        lastUpdatedAt:
          type: string
          format: date-time
        supply:
          type: number
          format: biginteger
        metaURL:
          type: string
          example: "ipfs://ipfs/QmPe1W8XiUYdsvdpvgWVwekQ7cDQivRMak3YPX15vxvSJs"
        meta:
          $ref: "#/components/schemas/Meta"
        deleted:
          type: boolean
      oneOf:
        - $ref: "#/components/schemas/EthItem"
        - $ref: "#/components/schemas/FlowItem"
      required:
        - mintedAt
        - lastUpdatedAt
        - supply
        - deleted

    Items:
      type: object
      properties:
        total:
          type: integer
          format: int64
          description: "Number of items were found by request"
        continuation:
          type: string
          description: "Continuation token to paginate items search result"
        items:
          type: array
          description: "List of found items"
          items:
            $ref: "#/components/schemas/Item"
      required:
        - "total"
        - "items"

    #################### Item - Eth ####################

    EthItem:
      type: object
      properties:
        "@type":
          type: string
          enum:
            - ETHEREUM
        blockchain:
          $ref: "#/components/schemas/EthBlockchain"
        id:
          $ref: "#/components/schemas/EthItemId"
        tokenId:
          type: number
          format: biginteger
        collection:
          $ref: "#/components/schemas/EthAddress"
        creators:
          type: array
          items:
            $ref: "#/components/schemas/EthCreator"
        owners:
          type: array
          items:
            $ref: "#/components/schemas/EthAddress"
        royalties:
          type: array
          items:
            $ref: "#/components/schemas/EthRoyalty"
        lazySupply:
          type: number
          format: biginteger
        pending:
          type: array
          items:
            $ref: "#/components/schemas/EthPendingItem"
      required:
        - "blockchain"
        - "id"
        - "tokenId"
        - "collection"
        - "creators"
        - "owners"
        - "royalties"
        - "lazySupply"

    EthRoyalty:
      type: object
      properties:
        account:
          $ref: "#/components/schemas/EthAddress"
        value:
          type: number
          format: biginteger

    EthCreator:
      type: object
      properties:
        account:
          $ref: "#/components/schemas/EthAddress"
        value:
          type: number
          format: bigdecimal
      required:
        - "account"
        - "value"

    EthPendingItem:
      type: object
      properties:
        type:
          type: string
          enum:
            - "TRANSFER"
        from:
          $ref: "#/components/schemas/EthAddress"
      required:
        - "type"
        - "from"

    #################### Ownership - Eth ####################

    EthPendingOwnershipTransfer:
      type: object
      properties:
        "@type":
          type: string
          enum:
            - TRANSFER
        from:
          $ref: "#/components/schemas/EthAddress"
      required:
        - "@type"
        - from

    EthPendingOwnershipRoyalty:
      type: object
      properties:
        "@type":
          type: string
          enum:
            - ROYALTY
        from:
          type: array
          items:
            $ref: "#/components/schemas/EthRoyalty"
      required:
        - "@type"
        - from

    EthPendingOwnership:
      type: object
      oneOf:
        - $ref: "#/components/schemas/EthPendingOwnershipTransfer"
        - $ref: "#/components/schemas/EthPendingOwnershipRoyalty"

    EthOwnership:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/EthOwnershipId"
        contract:
          $ref: "#/components/schemas/EthAddress"
        tokenId:
          type: number
          format: biginteger
        owner:
          type: array
          items:
            $ref: "#/components/schemas/EthAddress"
        creators:
          type: array
          items:
            $ref: "#/components/schemas/EthCreator"
        lazyValue:
          type: number
          format: biginteger
        pending:
          type: array
          items:
            $ref: "#/components/schemas/EthPendingOwnership"
      required:
        - id
        - contract
        - tokenId
        - owner
        - creators
        - lazyValue
        - pending

    #################### Item - Flow ####################

    FlowCreator:
      type: object
      properties:
        account:
          $ref: "#/components/schemas/FlowAddress"
        value:
          type: number
          format: bigdecimal
      required:
        - account
        - value

    FlowRoyalty:
      type: object
      properties:
        account:
          $ref: "#/components/schemas/FlowAddress"
        value:
          type: number
          format: bigdecimal
      required:
        - account
        - value

    FlowItem:
      type: object
      properties:
        "@type":
          type: string
          enum:
            - FLOW
        blockchain:
          type: string
          enum:
            - FLOW
        id:
          $ref: "#/components/schemas/FlowItemId"
        tokenId:
          type: number
          format: biginteger
        collection:
          $ref: "#/components/schemas/FlowContract"
        creators:
          type: array
          items:
            $ref: "#/components/schemas/FlowCreator"
        owners:
          type: array
          items:
            $ref: "#/components/schemas/FlowAddress"
        royalties:
          type: array
          items:
            $ref: "#/components/schemas/FlowRoyalty"
      required:
        - blockchain
        - id
        - tokenId
        - collection
        - creators
        - owners
        - royalties

    #################### Ownership - Flow ####################

    FlowOwnership:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/FlowOwnershipId"
        contract:
          $ref: "#/components/schemas/FlowContract"
        tokenId:
          type: number
          format: biginteger
        owner:
          type: array
          items:
            $ref: "#/components/schemas/FlowAddress"
      required:
        - id
        - contract
        - tokenId
        - owner

    #################### Referenced Types ####################

    EthAddress:
      type: string
      example: "0x60f80121c31a0d46b5279700f9df786054aa5ee5"
    EthBlockchain:
      type: string
      enum:
        - ETHEREUM
        - POLYGON
    EthItemId:
      type: string
      example: "{blockchain}:${collection}:${tokenId}"
    EthOwnershipId:
      type: string
      example: "${blockchain}:${collection}:${tokenId}:${owner}"

    FlowAddress:
      type: string
      example: "0x5c075acc71f2f41c"
    FlowContract:
      type: string
      example: "A.${FlowAddress}.${string}"
    FlowItemId:
      type: string
      example: "FLOW:${FlowAddress}:${tokenId}"
    FlowOwnershipId:
      type: string
      example: "${blockchain}:${collection}:${tokenId}:${owner}"

    Word:
      type: string
    Binary:
      type: string